src/app/app.component.html, src/app/app.module.ts, src/app/b-yadagiri/yadagiri-test/yadagiri-test.component.html, src/app/b-yadagiri/yadagiri-test/yadagiri-test.component.spec.ts, src/app/b-yadagiri/yadagiri-test/yadagiri-test.component.ts
I added my component for practice
=> Yadagiri Test change

src/app/app.module.ts, src/app/g-sandeep/sandeep-test/sandeep-test.component.html, src/app/g-sandeep/sandeep-test/sandeep-test.component.spec.ts, src/app/g-sandeep/sandeep-test/sandeep-test.component.ts
=> sandeep Test

angular.json, package-lock.json, package.json, src/app/Mohammad/mohammad/mohammad.component.html, src/app/Mohammad/mohammad/mohammad.component.scss, src/app/Mohammad/mohammad/mohammad.component.spec.ts, src/app/Mohammad/mohammad/mohammad.component.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/loginpage.service.spec.ts, src/app/loginpage.service.ts
=> Mohammad Login

angular.json, package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/app.module.ts, src/app/maheshreddy/mahesh-login/mahesh-login.component.html, src/app/maheshreddy/mahesh-login/mahesh-login.component.scss, src/app/maheshreddy/mahesh-login/mahesh-login.component.spec.ts, src/app/maheshreddy/mahesh-login/mahesh-login.component.ts, src/app/maheshreddy/services/login.service.spec.ts, src/app/maheshreddy/services/login.service.ts, src/index.html, src/styles.scss
=> mahesh-login

src/app/Mohammad/mohammad/MohammadDashboard/mohammad-dashboard/mohammad-dashboard.component.html, src/app/Mohammad/mohammad/MohammadDashboard/mohammad-dashboard/mohammad-dashboard.component.scss, src/app/Mohammad/mohammad/MohammadDashboard/mohammad-dashboard/mohammad-dashboard.component.spec.ts, src/app/Mohammad/mohammad/MohammadDashboard/mohammad-dashboard/mohammad-dashboard.component.ts, src/app/Mohammad/mohammad/mohammad.component.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/styles.scss
=> creating menus

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts, src/app/maheshreddy/mahesh-login/mahesh-login.component.ts, src/app/maheshreddy/maheshdashboard/maheshdashboard.component.html, src/app/maheshreddy/maheshdashboard/maheshdashboard.component.spec.ts, src/app/maheshreddy/maheshdashboard/maheshdashboard.component.ts, src/styles.scss
=> created menus

src/app/Mohammad/Child/child/child.component.html, src/app/Mohammad/Child/child/child.component.spec.ts, src/app/Mohammad/Child/child/child.component.ts, src/app/Mohammad/mohammad/MohammadDashboard/mohammad-dashboard/mohammad-dashboard.component.html, src/app/Mohammad/users/users/users.component.html, src/app/Mohammad/users/users/users.component.spec.ts, src/app/Mohammad/users/users/users.component.ts, src/app/app-routing.module.ts, src/app/app.module.ts
practiced on data flow between components
=> practiced on data flow between components

src/app/navya-module/Components/dashboard/dashboard.component.html, src/app/navya-module/Components/dashboard/dashboard.component.scss, src/app/navya-module/Components/dashboard/dashboard.component.ts, src/app/navya-module/Components/home-page/home-page.component.html, src/app/navya-module/Components/login/login.component.html, src/app/navya-module/Components/login/login.component.scss
=> Menus changes

src/app/app-routing.module.ts, src/app/dashboard/dashboard.component.html
=> Added routelink

src/app/nagarjuna-b/components/shopping/shopping.component.html, src/app/nagarjuna-b/components/shopping/shopping.component.spec.ts, src/app/nagarjuna-b/components/shopping/shopping.component.ts
=> added components

src/app/g-sandeep/sandeep-test/sandeep-test.component.html, src/app/g-sandeep/sandeep-test/sandeep-test.component.scss, src/app/g-sandeep/sandeep-test/sandeep-test.component.ts
=> login component with validations

src/app/U-Pranay/home/home.component.html, src/app/U-Pranay/home/home.component.spec.ts, src/app/U-Pranay/home/home.component.ts, src/app/U-Pranay/pranay/pranay-routing.module.ts, src/app/U-Pranay/pranay/pranay.module.ts, src/app/app.module.ts, src/app/dashboard/dashboard.component.html
=> pranay module added

src/app/Naresh/naresh-routing.module.ts, src/app/Naresh/naresh.module.ts, src/app/Naresh/naresh/naresh.component.html, src/app/app-routing.module.ts, src/app/app.module.ts
=> naresh routing module

src/app/U-Pranay/home/home.component.html, src/app/U-Pranay/home/home.component.ts, src/app/U-Pranay/pranay/pranay.module.ts, src/app/app.module.ts
=> pranaymodule

src/app/app.module.ts, src/app/dinesh/d-login/d-login.component.html, src/app/dinesh/d-login/d-login.component.ts, src/app/dinesh/dinesh-routing.module.ts, src/app/dinesh/dinesh.module.ts, src/app/dinesh/signup/signup.component.html, src/app/dinesh/signup/signup.component.spec.ts, src/app/dinesh/signup/signup.component.ts
=> Add routing and one component

src/app/Naresh/Decoretorsconsept/chaildcomponent/chaildcomponent.component.html, src/app/Naresh/Decoretorsconsept/chaildcomponent/chaildcomponent.component.scss, src/app/Naresh/Decoretorsconsept/chaildcomponent/chaildcomponent.component.spec.ts, src/app/Naresh/Decoretorsconsept/chaildcomponent/chaildcomponent.component.ts, src/app/Naresh/Decoretorsconsept/parentcomponent/parentcomponent.component.html, src/app/Naresh/Decoretorsconsept/parentcomponent/parentcomponent.component.scss, src/app/Naresh/Decoretorsconsept/parentcomponent/parentcomponent.component.spec.ts, src/app/Naresh/Decoretorsconsept/parentcomponent/parentcomponent.component.ts, src/app/Naresh/crudservises.service.ts, src/app/Naresh/maincomponent/maincomponent.component.html, src/app/Naresh/maincomponent/maincomponent.component.scss, src/app/Naresh/maincomponent/maincomponent.component.spec.ts, src/app/Naresh/maincomponent/maincomponent.component.ts, src/app/Naresh/naresh-routing.module.ts, src/app/Naresh/naresh.module.ts, src/app/Naresh/naresh/naresh.component.html
=> Decoraters Concept

src/app/U-Pranay/angularpractice/angularpractice.component.html, src/app/U-Pranay/angularpractice/angularpractice.component.spec.ts, src/app/U-Pranay/angularpractice/angularpractice.component.ts, src/app/U-Pranay/auth.service.spec.ts, src/app/U-Pranay/auth.service.ts, src/app/U-Pranay/home/home.component.html, src/app/U-Pranay/login/login.component.html, src/app/U-Pranay/login/login.component.spec.ts, src/app/U-Pranay/login/login.component.ts, src/app/U-Pranay/practice/practice.component.html, src/app/U-Pranay/practice/practice.component.spec.ts, src/app/U-Pranay/practice/practice.component.ts, src/app/U-Pranay/pranay/pranay-routing.module.ts, src/app/U-Pranay/pranay/pranay.module.ts, src/app/U-Pranay/register/register.component.html, src/app/U-Pranay/register/register.component.spec.ts, src/app/U-Pranay/register/register.component.ts, src/app/dashboard/dashboard.component.html
=> Child Routing

src/app/AdityaChandra/aditya/aditya-routing.module.ts, src/app/AdityaChandra/aditya/aditya.module.ts
=> added routing module

package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/dashboard/dashboard.component.html, src/app/nagarjuna-b/components/child/child.component.html, src/app/nagarjuna-b/components/child/child.component.spec.ts, src/app/nagarjuna-b/components/child/child.component.ts, src/app/nagarjuna-b/components/shopping/shopping.component.html, src/app/nagarjuna-b/components/shopping/shopping.component.ts, src/app/nagarjuna-b/nagarjuna-routing.module.ts, src/app/nagarjuna-b/nagarjuna.module.ts, src/styles.scss
=> added updated

src/app/app-routing.module.ts
=> Modifications
